{% set major_minor = "2.56" %}
{% set version = major_minor + ".2" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: glib
  version: {{ version }}

source:
  url: http://ftp.gnome.org/pub/GNOME/sources/glib/{{ major_minor }}/glib-{{ version }}.tar.xz
  sha256: d64abd16813501c956c4e123ae79f47f1b58de573df9fdd3b0795f1e2c1aa789
  patches:
    # Related to this patch https://bugzilla.gnome.org/show_bug.cgi?id=673135
    # However, it was rejected by upstream. Homebrew decided to keep their own
    # copy ( https://raw.githubusercontent.com/Homebrew/patches/59e4d32/glib/hardcoded-paths.diff ).
    # We are essentially using that copy, but with some tweaks. Info at the link below.
    #
    # https://github.com/Homebrew/legacy-homebrew/blob/21ce7a56cb3fc40fe93d731cc654c69268796772/Library/Formula/glib.rb#L33-L39
    #
    - hardcoded-paths.patch
    # Not sure why test_stdio_wrappers do not pass, skipping it for now.
    - no_fileutils_test.patch
    # Windows:
    - 0001-Manually-link-with-libiconv-whenever-we-use-libintl.patch  # [win]
    - 0002-Increase-some-test-timeouts.patch                          # [win]

build:
  number: 1000
  skip: True  # [not py36]
  detect_binary_files_with_prefix: True
  run_exports:
    - {{ pin_subpackage('glib') }}

requirements:
  build:
    - {{posix}}patch  # [win]
    - ninja           # [win]
    - {{native}}pkg-config
    - {{ compiler('c') }}
  host:
    # The meson version pin is to avoid a buggy package; see
    # meson-feedstock issue #11.
    - meson <0.48  # [win]
    - python
    - libffi
    - gettext
    - zlib
    - pcre
    - libiconv
  run:
    - libffi
    - gettext
    - zlib
    - pcre
    - libiconv

test:
  commands:
    - test -f ${PREFIX}/lib/libglib-2.0{{ SHLIB_EXT }}  # [not win]
    - test ! -f ${PREFIX}/lib/libgobject-2.0.la  # [not win]
    - conda inspect linkages -p $PREFIX $PKG_NAME  # [not win]
    - conda inspect objects -p $PREFIX $PKG_NAME  # [osx]

about:
  home: https://developer.gnome.org/glib/
  license: LGPL-2.1
  license_file: COPYING
  summary: 'Provides core application building blocks for libraries and applications written in C.'

extra:
  recipe-maintainers:
    - ccordoba12
    - jakirkham
    - scopatz
    - ocefpaf
    - pkgw
